### ISSUE TITLE
收藏只有一页，希望加多，以及增加分类收藏的功能

### ISSUE THREAD

**Issue by 952xuan** [tonquer/JMComic-qt#1]
### 功能描述（请清晰的、详细的描述你想要的功能）
> 如题

### 附加信息（其他的与功能相关的附加信息）
> 

### 效果演示（可以提供可借鉴的图片）
>

**Comment by Ltyro** [comment]
连不上，是要翻墙吗

**Comment by tonquer** [comment]
v1.0.2已支持该功能
