### ISSUE TITLE
mac端的搜索页面标签显示不全

### ISSUE THREAD

**Issue by flappybriefs** [tonquer/JMComic-qt#10]
### 操作系统（如MacOS 10.15）
> macOS 12.4 beta2

### 网络环境（移动，联通，电信，移动宽带，联通宽带，电信宽带，等等..）
>网络正常

### 问题描述（简要描述发生的问题）
> mac端的搜索页面标签显示不全

### 复现步骤（详细描述导致问题产生的操作步骤，如果能稳定复现）
> 随便打开一个漫画就是这样的

### 日志提交（问题截图或者日志，日志在logs目录）
> 
<img width="1462" alt="image" src="https://user-images.githubusercontent.com/35480800/164142174-3c346419-771c-4167-b9cf-0ecef288877b.png">

**Comment by tonquer** [comment]
下版本修复

**Comment by tonquer** [comment]
已修复
