### ISSUE TITLE
网络错误

### ISSUE THREAD

**Issue by mishideweilai** [tonquer/JMComic-qt#102]
### 操作系统（如MacOS 10.15）
>
WIN10

### 网络环境（移动，联通，电信，移动宽带，联通宽带，电信宽带，等等..）
>
移動

### 问题描述（简要描述发生的问题）
>
![image](https://github.com/tonquer/JMComic-qt/assets/116932664/e37041e5-ed1d-4f85-8e77-2815b0a47e2d)

### 复现步骤（详细描述导致问题产生的操作步骤，如果能稳定复现）
>
连着几天都是这样还以为是网络波动造成的

### 日志提交（问题截图或者日志，日志在logs目录）
>
无。。。

**Comment by tonquer** [comment]
上传下日志看看

**Comment by mishideweilai** [comment]
[20240521.log](https://github.com/tonquer/JMComic-qt/files/15391548/20240521.log)

**Comment by tonquer** [comment]
> [20240521.log](https://github.com/tonquer/JMComic-qt/files/15391548/20240521.log)
> 
> 

看日志是无法解析域名，可能是dns的问题，可以换个公共dns试试

**Comment by mishideweilai** [comment]
> > [20240521.log](https://github.com/tonquer/JMComic-qt/files/15391548/20240521.log)
> 
> 看日志是无法解析域名，可能是dns的问题，可以换个公共dns试试

114.114.114.114和8.8.8.8就可以了嗎？小白，请大佬指教。

**Comment by tonquer** [comment]
> > > [20240521.log](https://github.com/tonquer/JMComic-qt/files/15391548/20240521.log)
> > 
> > 
> > 看日志是无法解析域名，可能是dns的问题，可以换个公共dns试试
> 
> 114.114.114.114和8.8.8.8就可以了嗎？小白，请大佬指教。

可以试试用114的

**Comment by mishideweilai** [comment]
> > > > [20240521.log](https://github.com/tonquer/JMComic-qt/files/15391548/20240521.log)
> > > 
> > > 
> > > 看日志是无法解析域名，可能是dns的问题，可以换个公共dns试试
> > 
> > 
> > 114.114.114.114和8.8.8.8就可以了嗎？小白，请大佬指教。
> 
> 可以试试用114的
试了下114和8，有一个可以用了，但是其他线还是不行，一直会这样吗？非常感谢大佬得耐心解答
![image](https://github.com/tonquer/JMComic-qt/assets/116932664/9115bba9-dfde-403d-a522-2f74232aa8a1)

**Comment by tonquer** [comment]
再上传下日志我看看

**Comment by mishideweilai** [comment]
> 再上传下日志我看看
[20240522.log](https://github.com/tonquer/JMComic-qt/files/15404575/20240522.log)
辛苦大佬！

**Comment by tonquer** [comment]
看上去是JM的域名被SNI拦截了，这周会出个更新，加个反代分流试试

**Comment by mishideweilai** [comment]
> 看上去是JM的域名被SNI拦截了，这周会出个更新，加个反代分流试试

好的，谢谢大佬
