### ISSUE TITLE
waifu2x 有时显示的图片会不正常

### ISSUE THREAD

**Issue by OvOooooooo** [tonquer/JMComic-qt#103]
### 操作系统（如MacOS 10.15）
> Windows 11 专业版 26217（24H2）

### 网络环境（移动，联通，电信，移动宽带，联通宽带，电信宽带，等等..）
> 移动宽带、联通 5g 手机流量开热点都试过，都有时会出现这个问题。

### 问题描述（简要描述发生的问题）
> 当使用浏览器端的 “开始阅读” 模式时，不少图刚显示时是一张 “被拆成一条条，并从下到上反过来拼在一起” 的图片，不过不管浏览器还是客户端，稍微等待一下都会替换正常图片。

> **但是在客户端内，这种错误拼接的图一出现就会直接被存进缓存文件夹，如果打开 waifu2x ，会直接处理这些缓存并显示出来。**

> p.s.在浏览器端用 “分页阅读” 模式时，貌似会直接从上到下加载全图。（未验证）

### 复现步骤（详细描述导致问题产生的操作步骤，如果能稳定复现）
> 客户端打开一本漫画，开 waifu2x，快速翻页直至最后，等全部加载完，中间很多页有概率变成这种图

### 日志提交（问题截图或者日志，日志在logs目录）
> 这是一本漫画的部分缓存图，可以看到很多图都一条一条的
![image](https://github.com/tonquer/JMComic-qt/assets/38456160/9cc2c338-7a80-4a4d-aed1-364b02368771)

> 这是其中一张图的对比
![image](https://github.com/tonquer/JMComic-qt/assets/38456160/0dc89472-6256-4aea-90cd-0f48bdc06e65)
   不开 waifu2x 就能正常显示
![image](https://github.com/tonquer/JMComic-qt/assets/38456160/078092fb-7c00-4b8b-95d4-a929773457b2)

> 日志文件
[20240524.log](https://github.com/tonquer/JMComic-qt/files/15432014/20240524.log)

**Comment by tonquer** [comment]
修复了，试试
https://github.com/tonquer/JMComic-qt/releases/tag/v1.2.2

**Comment by OvOooooooo** [comment]
好了，感谢🙇🙏
