### ISSUE TITLE
缓存和下载路径可以设置为相对路径

### ISSUE THREAD

**Issue by DentistCode** [tonquer/JMComic-qt#109]
### 功能描述（请清晰的、详细的描述你想要的功能）
> 下载和缓存能够开一个选项：默认设置为相对路径，直接存在工作文件夹里，方便外接硬盘党（瑟瑟和正经分开x），因为外接硬盘多了之后，外接的硬盘盘符不会固定。

### 附加信息（其他的与功能相关的附加信息）
> 

### 效果演示（可以提供可借鉴的图片）
>
![image](https://github.com/user-attachments/assets/5dba8429-ec37-412e-b16f-04a1aecdf467)

**Comment by DentistCode** [comment]
否则每次本地漫画都会失效
![Snipaste_2024-07-12_16-39-52](https://github.com/user-attachments/assets/71ae13d5-4db3-421a-8657-96d00debfb5c)

**Comment by tonquer** [comment]
你可以把移动硬盘设置固定盘符，设置后面字母的，重新插是不会变的
