### ISSUE TITLE
已下载的漫画无法打开阅读

### ISSUE THREAD

**Issue by Porco1987** [tonquer/JMComic-qt#111]
### 操作系统（如MacOS 10.15）
> Windows 10

### 网络环境（移动，联通，电信，移动宽带，联通宽带，电信宽带，等等..）
> 电信宽带

### 问题描述（简要描述发生的问题）
> 打开已下载的漫画，无法观看。
V1.2.3版本仍然有此问题，之前也一直有，没来得及报。

### 复现步骤（详细描述导致问题产生的操作步骤，如果能稳定复现）
> 一直都有，要复现可能要换机器。

### 日志提交（问题截图或者日志，日志在logs目录）
> ![image](https://github.com/user-attachments/assets/b93cd23c-2f77-41f5-b8f1-d1807685fb52)

**Comment by tonquer** [comment]
建议先在下载界面右键导入到本地漫画中观看

**Comment by tonquer** [comment]
v1.2.5已修复
