### ISSUE TITLE
每次看的时候切换全屏都要黑屏一下，但是一样的哔咔就没有这个问题

### ISSUE THREAD

**Issue by Yi1Nai** [tonquer/JMComic-qt#112]
### 操作系统（如MacOS 10.15）
>win11

### 网络环境（移动，联通，电信，移动宽带，联通宽带，电信宽带，等等..）
>电信

### 问题描述（简要描述发生的问题）
>观看选择全屏的时候总要黑屏一下，退出去也是，但是用一样的哔咔就没这样

### 复现步骤（详细描述导致问题产生的操作步骤，如果能稳定复现）
>

### 日志提交（问题截图或者日志，日志在logs目录）
>

**Comment by tonquer** [comment]
都是最新版吗，是闪屏一下正常这样吗

**Comment by Yi1Nai** [comment]
两个都是最新版，对，就只有jm切全屏和退出闪屏一下

> 都是最新版吗，是闪屏一下正常这样吗
