### ISSUE TITLE
单页漫画和系统界面全屏模式下显示错误

### ISSUE THREAD

**Issue by hskshd** [tonquer/JMComic-qt#114]
全屏模式下如图1图2，
缩放100时漫画的最下面超出显示器
![1](https://github.com/user-attachments/assets/fb0a0395-3269-4d6a-99b9-e797bbad10e2)

缩放到90才能显示单页漫画的全部（上下没对齐看着难受）
![2](https://github.com/user-attachments/assets/cd66cac2-9bd6-4b6d-ba1c-6bde8f741d0c)

界面也有问题，如图3，
最下面的设置分类的东西超出显示器范围，但可以点击到
![3 ](https://github.com/user-attachments/assets/0a8f55bf-1aa7-4123-8ecd-7294742e53fd)

**Comment by hskshd** [comment]
1920x1080,125％（初始设定推荐），对不起现在才看到

获取Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by hskshd** [comment]
我没有动过这里两个设置，是突然出现问题的。

获取Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by tonquer** [comment]
v1.2.5已修复
