### ISSUE TITLE
希望更改加載動畫

### ISSUE THREAD

**Issue by smalllqiang** [tonquer/JMComic-qt#115]
### 功能描述（请清晰的、详细的描述你想要的功能）
> 似乎使用了嗶咔的加載動畫
希望能更改為JM的

### 附加信息（其他的与功能相关的附加信息）
> 

### 效果演示（可以提供可借鉴的图片）
>
![app_images_loading](https://github.com/user-attachments/assets/36f93cb3-0cb2-424e-8b87-2467ade364bb)

**Comment by tonquer** [comment]
v1.2.5已支持
