### ISSUE TITLE
无法登录并弹窗显示“Enable JavaScript and cookies to continue”

### ISSUE THREAD

**Issue by ZongPou** [tonquer/JMComic-qt#118]
### 操作系统（如MacOS 10.15）
>Windows10 22H2

### 网络环境（移动，联通，电信，移动宽带，联通宽带，电信宽带，等等..）
>移动宽带

### 问题描述（简要描述发生的问题）
>尝试登录时弹窗“Enable JavaScript and cookies to continue”，关闭登录页面后弹窗“无法解析”

### 复现步骤（详细描述导致问题产生的操作步骤，如果能稳定复现）
>每次都会出现，现已无法使用

### 日志提交（问题截图或者日志，日志在logs目录）
>
[20240821.log](https://github.com/user-attachments/files/16689766/20240821.log)

**Comment by tonquer** [comment]
域名已更新，请重新打开本软件自动更新域名
