### ISSUE TITLE
检查更新按钮不可用

### ISSUE THREAD

**Issue by Lkhsss** [tonquer/JMComic-qt#12]
### 操作系统（如MacOS 10.15）
>windows11

### 网络环境（移动，联通，电信，移动宽带，联通宽带，电信宽带，等等..）
>移动宽带

### 问题描述（简要描述发生的问题）
>没法点击“检查更新”按钮，看起来这个按钮只是放了个图片上去。

### 复现步骤（详细描述导致问题产生的操作步骤，如果能稳定复现）
>点击“检查更新”按钮

### 日志提交（问题截图或者日志，日志在logs目录）
>

**Comment by tonquer** [comment]
v1.0.6已修复
