### ISSUE TITLE
在漫画详情页点击已下载章节下面的漫画时会报错

### ISSUE THREAD

**Issue by shenmeshisanpao** [tonquer/JMComic-qt#123]
### 操作系统（如MacOS 10.15）
>
windows 11

### 网络环境（移动，联通，电信，移动宽带，联通宽带，电信宽带，等等..）
>
移动宽带

### 问题描述（简要描述发生的问题）
>
在漫画详情页点击已下载章节下面的漫画时会报错:
Traceback (most recent call last):
  File "view\info\book_info_view.py", line 420, in OpenReadImg2
AttributeError: 'PySide6.QtWidgets.QListWidgetItem' object has no attribute 'index'

但可以点击 可离线阅读已下载的章节 后面的按钮看

### 复现步骤（详细描述导致问题产生的操作步骤，如果能稳定复现）
>
点进漫画详情
点击“已下载章节”
点击“1-第1话”
出现错误

### 日志提交（问题截图或者日志，日志在logs目录）
>
![1728394823758](https://github.com/user-attachments/assets/3eda7460-7e5a-404f-9a81-1dbfcc3d4faf)

**Comment by tonquer** [comment]
v1.2.5已修复
