### ISSUE TITLE
几乎所有API均返回403，`<!DOCTYPE html><html lang="en-US"><head><title>Just a moment...</title>`

### ISSUE THREAD

**Issue by lanyeeee** [tonquer/JMComic-qt#124]
### 操作系统（如MacOS 10.15）
> Windows11
> 软件版本为最新的[v1.2.3](https://github.com/tonquer/JMComic-qt/releases/tag/v1.2.3)

### 网络环境（移动，联通，电信，移动宽带，联通宽带，电信宽带，等等..）
> 电信宽带(使用科技)

### 问题描述（简要描述发生的问题）
> 几乎所有API(登录、获取首页等)均返回403，内容大致如下
> ```
> code:403, text:<!DOCTYPE html><html lang="en-US"><head><title>Just a moment...</title>
> ```
> 我自己尝试了10余条科技线路，可以正常使用访问官方的APP，但是在这里均返回403
> ~~分流2有概率能登录成功，可能10次有1次这样？不过即使登录成功后，获取首页也是10次成功1次的样子，且非常卡~~

### 复现步骤（详细描述导致问题产生的操作步骤，如果能稳定复现）
> 1. 双击`start.exe`打开软件
> 2. 输入用户名密码，点击确定
> 3. 登录失败，提示`Enable JavaScript and cookies to continue`
> ![image](https://github.com/user-attachments/assets/177e89a6-4e8d-4cb9-a611-70afd8451273)

### 日志提交（问题截图或者日志，日志在logs目录）
> [20241009.log](https://github.com/user-attachments/files/17310794/20241009.log)

### 补充
> 看日志是因为jm那边的`5秒盾`导致的JSON解析错误
> 所以我觉得有两种可能
> 1. jm最近给接口加了`5秒盾`
> 2. 我所尝试的所有科技线路都在jm那边风控了

**Comment by tonquer** [comment]
已更新，重新打开本软件更新域名

**Comment by lanyeeee** [comment]
亲测可用
