### ISSUE TITLE
程序启动后页面无法加载，数秒后闪退

### ISSUE THREAD

**Issue by GELIN411** [tonquer/JMComic-qt#127]
### 操作系统（如MacOS 10.15）
>Windows 11 专业版  21H2

### 网络环境（移动，联通，电信，移动宽带，联通宽带，电信宽带，等等..）
>移动宽带

### 问题描述（简要描述发生的问题）
>程序在启动后页面无法加载，并且几秒后闪退，10月12及以前是可以正常使用的，13日开始出现上述问题

### 复现步骤（详细描述导致问题产生的操作步骤，如果能稳定复现）
>无特殊步骤，就是正常启动

### 日志提交（问题截图或者日志，日志在logs目录）
>
<img width="959" alt="屏幕截图 2024-10-14 093232" src="https://github.com/user-attachments/assets/cf50d064-df8e-43b2-b76b-e02d0b7088de">
[20241014.log](https://github.com/user-attachments/files/17358053/20241014.log)

**Comment by tonquer** [comment]
把目录下data打包，发我邮件看看tonquer@qq.com

**Comment by tonquer** [comment]
v1.2.5已支持
