### ISSUE TITLE
关于官网

### ISSUE THREAD

**Issue by guaiguaigou** [tonquer/JMComic-qt#133]
![屏幕截图 2024-11-13 151939](https://github.com/user-attachments/assets/7613e90a-b440-470d-92ac-1e599cd521a0)

你好，点开官网就显示这个，导致注册之后不能确认

**Comment by tonquer** [comment]
日本ip？

**Comment by guaiguaigou** [comment]
嗯嗯，在日本

**Comment by tonquer** [comment]
JM网页版禁止日本ip访问，你可以把验证链接发我邮箱tonquer@qq.com，我可以帮你点一下

**Comment by guaiguaigou** [comment]
okok，义父
