### ISSUE TITLE
我的收藏忽然看不到

### ISSUE THREAD

**Issue by ericvlog** [tonquer/JMComic-qt#15]
### 操作系统（如MacOS 10.15）
> windows 10 pro

### 网络环境（移动，联通，电信，移动宽带，联通宽带，电信宽带，等等..）
> 外网

### 问题描述（简要描述发生的问题）
> 忽然今天按了我的收藏，但一片空白

### 复现步骤（详细描述导致问题产生的操作步骤，如果能稳定复现）
> 打开软件，登入成功，我的收藏。

### 日志提交（问题截图或者日志，日志在logs目录）
>

**Comment by tonquer** [comment]
官方App也看不到，只有网页版才能看见，因为用的是APP的api，下版本考虑加入网页版的api。

**Comment by ericvlog** [comment]
> 官方App也看不到，只有网页版才能看见，因为用的是APP的api，下版本考虑加入网页版的api。

那好的，谢谢分享那么好的软件。

**Comment by tonquer** [comment]
v1.0.6已修复
