### ISSUE TITLE
查看已经下载好的漫画

### ISSUE THREAD

**Issue by zhiyiYo** [tonquer/JMComic-qt#16]
### 功能描述
> 1. 请问下载好漫画之后，在界面里面打开这个漫画，载入的是下载好的图片还是重新发请求下载的？
> 2. 如果打开的是下载好的漫画且下载时候已经使用 waifu2x 转换过了，为啥打开漫画之后还是显示正在转换的提示

**Comment by tonquer** [comment]
1、是重新请求的
2、好像没有做优先读取下载转换好的waifu2x文件

**Comment by zhiyiYo** [comment]
蹲一个观看已下载漫画功能😇

**Comment by tonquer** [comment]
新建文件夹（1）

**Comment by zhiyiYo** [comment]
> 新建文件夹（1）

？

**Comment by tonquer** [comment]
下个版本应该会加上

**Comment by machunhui1443** [comment]
首页显示：网络错误，请检查网络代理，是咋回事

**Comment by tonquer** [comment]
> 首页显示：网络错误，请检查网络代理，是咋回事

点登陆-分流 试试其他分流

**Comment by tonquer** [comment]
v1.0.6发布，支持离线模式
