### ISSUE TITLE
下载完成后waiu2x转换失败，提示文件损坏，但是下载目录里图片可以打开

### ISSUE THREAD

**Issue by 349545415** [tonquer/JMComic-qt#17]
### 操作系统（如MacOS 10.15）
>win10

### 网络环境（移动，联通，电信，移动宽带，联通宽带，电信宽带，等等..）
>电信

### 问题描述（简要描述发生的问题）
>下载完成后waiu2x转换失败，提示文件损坏，但是下载目录里图片可以打开

### 复现步骤（详细描述导致问题产生的操作步骤，如果能稳定复现）
>最新的本子都不行

### 日志提交（问题截图或者日志，日志在logs目录）
>

**Comment by tonquer** [comment]
貌似新的图片都改成webp格式了，下个版本支持webp格式，[waifu2x v1.1.2](https://github.com/tonquer/waifu2x-vulkan/releases/tag/v1.1.2)

**Comment by 349545415** [comment]
> 貌似新的图片都改成webp格式了，下个版本支持webp格式，[waifu2x v1.1.2](https://github.com/tonquer/waifu2x-vulkan/releases/tag/v1.1.2)

啊？我看下载下来都是jpg格式啊，那什么时候更新

**Comment by tonquer** [comment]
> > 貌似新的图片都改成webp格式了，下个版本支持webp格式，[waifu2x v1.1.2](https://github.com/tonquer/waifu2x-vulkan/releases/tag/v1.1.2)
> 
> 啊？我看下载下来都是jpg格式啊，那什么时候更新

jpg后缀是因为不支持的格式 统一设置成jpg后缀了

**Comment by tonquer** [comment]
等下提交一个更新，就可以了

**Comment by tonquer** [comment]
你可以下载试试
https://github.com/tonquer/JMComic-qt/actions/runs/2829858846

**Comment by NiuXZi** [comment]
> 你可以下载试试 https://github.com/tonquer/JMComic-qt/actions/runs/2829858846
这里面的文件已经过期了，可以重新发下吗？

**Comment by tonquer** [comment]
> > 你可以下载试试 https://github.com/tonquer/JMComic-qt/actions/runs/2829858846
> > 这里面的文件已经过期了，可以重新发下吗？

正在更新1.1.6版本，等下会发布下载链接

**Comment by tonquer** [comment]
> > 你可以下载试试 https://github.com/tonquer/JMComic-qt/actions/runs/2829858846
> > 这里面的文件已经过期了，可以重新发下吗？

已发布
https://github.com/tonquer/JMComic-qt/releases/tag/v1.0.6
