### ISSUE TITLE
搜索页页面样式

### ISSUE THREAD

**Issue by qwerty1874** [tonquer/JMComic-qt#20]
### 操作系统（如MacOS 10.15）
> win11 21H2，软件1.0.6

### 问题描述（简要描述发生的问题）
> 搜索页额头过大，是宽屏的问题吗？
![_4%6C}_HS1XQ99 XH2X3Y41](https://user-images.githubusercontent.com/47471816/187876149-0c0fa346-ce50-4a82-8559-ea7e7844528d.png)

**Comment by tonquer** [comment]
你是带鱼屏吗

**Comment by qwerty1874** [comment]
@tonquer 是的，21:9的屏幕

**Comment by tonquer** [comment]
已解决
