### ISSUE TITLE
动图好像加载有问题欸

### ISSUE THREAD

**Issue by JosephDemo** [tonquer/JMComic-qt#24]
### 操作系统（如MacOS 10.15）
>Windows10

### 网络环境（移动，联通，电信，移动宽带，联通宽带，电信宽带，等等..）
>移动

### 问题描述（简要描述发生的问题）
>MANA老师有一些Live2D的动图 好像加载有一些问题

### 复现步骤（详细描述导致问题产生的操作步骤，如果能稳定复现）
>搜索MANA 找到标题后带有L2D的（如夜兰L2D） 到动图时加载缓慢 加载出来也是异常的黑白图片

### 日志提交（问题截图或者日志，日志在logs目录）
>

**Comment by tonquer** [comment]
这个版本应该是还没支持动图的，没想到禁漫有动图

**Comment by JosephDemo** [comment]
那那以后会吗 大神

**Comment by Grey-Wind** [comment]
大神，下个版本什么时候好啊

**Comment by tonquer** [comment]
> 大神，下个版本什么时候好啊

明天或者后天
