### ISSUE TITLE
保存图片倒置

### ISSUE THREAD

**Issue by JosephDemo** [tonquer/JMComic-qt#27]
### 操作系统（如MacOS 10.15）
>
Windows10

### 网络环境（移动，联通，电信，移动宽带，联通宽带，电信宽带，等等..）
>移动

### 问题描述（简要描述发生的问题）
>右键复制保存的文件显示不正常 是类似百叶窗的分割形态 每个片段都正立 整体倒置

### 复现步骤（详细描述导致问题产生的操作步骤，如果能稳定复现）
>右键 复制 在复制到剪贴板和保存文件中选择保存文件 稍后在目录查看文件

### 日志提交（问题截图或者日志，日志在logs目录）
>
![20221202144415](https://user-images.githubusercontent.com/118981340/205232669-1bbfbfe4-a493-45b8-85e2-77fade2ec41a.jpg)

**Comment by tonquer** [comment]
v1.0.8已修复
