### ISSUE TITLE
图片因未知原因位置偏右

### ISSUE THREAD

**Issue by Grey-Wind** [tonquer/JMComic-qt#29]
Win10

**Comment by Grey-Wind** [comment]
![微信截图_20230203115512](https://user-images.githubusercontent.com/98391767/216509022-5c489d82-c047-4327-94bc-4a3921ae12ea.png)

**Comment by Grey-Wind** [comment]
主要显示如此
我所有的漫画都是这样显示的

**Comment by Grey-Wind** [comment]
疑似1.0.7版本问题，1.0.6版本无此问题
我现在重装1.0.7版本测试
如果仍有此bug我将会回滚至1.0.6测试

**Comment by tonquer** [comment]
是滚动模式吗，滚动模式有bug未修复

**Comment by Grey-Wind** [comment]
是滚动模式

**Comment by tonquer** [comment]
下个版本解决，你可以先不用滚动模式看图

**Comment by Grey-Wind** [comment]
好的

**Comment by Grey-Wind** [comment]
@tonquer 可以将改动或者bug修复实时同步到Github吗，不然每次都觉得项目凉了qaq

**Comment by buiawpkgew1** [comment]
> @tonquer 可以将改动或者bug修复实时同步到Github吗，不然每次都觉得项目凉了qaq

你是说Pr？

**Comment by tonquer** [comment]
v1.0.8已修复
