### ISSUE TITLE
JMComic的 打开分流设置点击无反应，不能用。

### ISSUE THREAD

**Issue by matocool** [tonquer/JMComic-qt#32]
### 操作系统（如MacOS 10.15）
>WIN10

### 网络环境（移动，联通，电信，移动宽带，联通宽带，电信宽带，等等..）
>移动

### 问题描述（简要描述发生的问题）
>[JMComic-qt](https://github.com/tonquer/JMComic-qt)的 打开分流设置点击无反应，不能用。

而作者开发的picacg则有效。

### 复现步骤（详细描述导致问题产生的操作步骤，如果能稳定复现）
>
![image](https://user-images.githubusercontent.com/83129369/213880152-8048699a-a917-4f9b-be87-6beea740bf78.png)
![image](https://user-images.githubusercontent.com/83129369/213880156-ed61962e-6fc3-437f-b285-231ff5bcb21c.png)

### 日志提交（问题截图或者日志，日志在logs目录）
>
[20230122.log](https://github.com/tonquer/JMComic-qt/files/10472703/20230122.log)

**Comment by matocool** [comment]
只能在登入那边，先退出。再设置好才能登入。为何不能像picacg那样。。。

**Comment by tonquer** [comment]
待修复

**Comment by tonquer** [comment]
v1.0.8已修复
