### ISSUE TITLE
上下滚动模式图片显示不全

### ISSUE THREAD

**Issue by jackeywcy** [tonquer/JMComic-qt#34]
### 操作系统（如MacOS 10.15）
>Windows 10

### 网络环境（移动，联通，电信，移动宽带，联通宽带，电信宽带，等等..）
>移动

### 问题描述（简要描述发生的问题）
>请见附件1，上下滚动模式图片仅显示左边部分

![图片](https://user-images.githubusercontent.com/20952447/214520420-a89f2c54-e405-487a-bed7-429eaaf664a1.png)

### 复现步骤（详细描述导致问题产生的操作步骤，如果能稳定复现）
> 

1.   打开JMcomic
2. 打开漫画，右键后选择上下滚动
3. 刷新后，页面漫画显示不全

### 日志提交（问题截图或者日志，日志在logs目录）
>
![图片](https://user-images.githubusercontent.com/20952447/214520816-662eb492-c62d-4f91-b882-a6bd4a468ed0.png)

**Comment by tonquer** [comment]
已知 待修复
