### ISSUE TITLE
图片加载后出现分裂

### ISSUE THREAD

**Issue by DFYun123** [tonquer/JMComic-qt#36]
### 操作系统（如MacOS 10.15）
>Windows 10

### 网络环境（移动，联通，电信，移动宽带，联通宽带，电信宽带，等等..）
>电信宽带

### 问题描述（简要描述发生的问题）
>2023年2月8日23时35分图片加载后出现分裂

### 复现步骤（详细描述导致问题产生的操作步骤，如果能稳定复现）
>

### 日志提交（问题截图或者日志，日志在logs目录）
>
![image](https://user-images.githubusercontent.com/89192168/217576046-f028632e-a646-4f9b-ae03-883a1c43a8ce.png)

**Comment by DFYun123** [comment]
仅2月8日后的新作品出现此问题

**Comment by AragonSnow** [comment]
2月8号后改了图片切割算法，后面新增的分割都会出现问题

**Comment by AragonSnow** [comment]
> 在上个版本我就发现问题
> 
> 在看任意漫画时候，软件内部显示正常，下载显示也是正常。。。
> 
> 但是在缓存里面，全部都是这种分裂的。。。

因为下载下来的图片就是乱序的，保存在缓存里没有重排而已，应该不算bug吧，不过2月8日后改了分割算法，导致后面上传的图片全部乱了

**Comment by tonquer** [comment]
预计周末修复

**Comment by AragonSnow** [comment]
> 预计周末修复

看了一下，photo id > 421926, 由原来的10求余，变成8求余，其他的不变

**Comment by tonquer** [comment]
> > 预计周末修复
> 
> 看了一下，photo id > 421926, 由原来的10求余，变成8求余，其他的不变

![6E4A5AE0](https://user-images.githubusercontent.com/22116659/217998518-663b0031-fb71-4e64-839f-02a5695875f4.png)

**Comment by tonquer** [comment]
v1.0.8已修复
