### ISSUE TITLE
#29 未修复

### ISSUE THREAD

**Issue by matocool** [tonquer/JMComic-qt#38]
https://github.com/tonquer/JMComic-qt/issues/29 未修复

阅读方式为默认，并非滚动。。而且测试了所有阅读方式，全部偏右

![218419755-cc6bcc54-3062-44ff-a19f-f93e570240fb](https://user-images.githubusercontent.com/83129369/218420170-961bd853-a5b9-449a-ac0f-0df539c58b9a.png)
![218419206-49fc99dc-2ab4-4cbc-bd9f-6589a9352184](https://user-images.githubusercontent.com/83129369/218420183-d8a7753d-cab2-41ed-8a27-e0a5d7e77d61.png)

**Comment by tonquer** [comment]
试试新的
https://github.com/tonquer/JMComic-qt/releases/tag/v1.0.9
