### ISSUE TITLE
漫画详情页小bug

### ISSUE THREAD

**Issue by matocool** [tonquer/JMComic-qt#41]
1、tags下面多了个 观看数

2、爱心数 观看数 被遮挡了部分。。。不如把爱心数 观看数并排处理。多的空间还可以另作他用。

![image](https://user-images.githubusercontent.com/83129369/218482532-353f0d64-9527-4575-bc66-0ae4b916ef46.png)

**Comment by tonquer** [comment]
> 界面缩放都试过了。。无效
> 
> ![image](https://user-images.githubusercontent.com/83129369/218483565-61844137-5d54-43b4-ab28-4f19d0395aae.png)

这个缩放改了 需要重新打开软件的

**Comment by tonquer** [comment]
已解决
