### ISSUE TITLE
作者大大你好，请问JM可以像pika那样支持自定义cdn分流吗？

### ISSUE THREAD

**Issue by matocool** [tonquer/JMComic-qt#43]
最近通过【CloudflareSpeedTest】找了几个CDN测速以及实际体验很快。

在pika那边用着很舒服，基本实现秒开

虽然JM也不慢，但是想追求更快的速度就得通过支持自定义分流了。不懂是不是JM那边不支持。。。

![image](https://user-images.githubusercontent.com/83129369/218849352-70d4646f-ed7c-4f5b-a0fa-c893093156b4.png)
![image](https://user-images.githubusercontent.com/83129369/218849383-66f89144-3de5-45d3-ac48-645db750f2d4.png)

**Comment by tonquer** [comment]
禁漫也用的cloudflare，应该是可以用CDN分流的

**Comment by tonquer** [comment]
已解决
