### ISSUE TITLE
下载出错BUG

### ISSUE THREAD

**Issue by JustTestCode** [tonquer/JMComic-qt#44]
### 操作系统（如MacOS 10.15）
>
win11

### 网络环境（移动，联通，电信，移动宽带，联通宽带，电信宽带，等等..）
>
电信

### 问题描述（简要描述发生的问题）
>
两个错误，

第一个是下载一半出错，等个10来分钟又能下一点，然后又错，测试过日志里的图片地址可以正常打开。

第二个错误，其中一个漫画无论怎么样都下载不了，卡在某个章节

### 复现步骤（详细描述导致问题产生的操作步骤，如果能稳定复现）
>

### 日志提交（问题截图或者日志，日志在logs目录）
>
![22](https://user-images.githubusercontent.com/65500757/218991537-ea1a6ce8-5943-48ae-8b94-d52aa6c35651.png)

**Comment by tonquer** [comment]
请贴一下漫画id

**Comment by JustTestCode** [comment]
第一个 272886
第二个
146417

日志里貌似有吧
