### ISSUE TITLE
Mac 软件格式不对。

### ISSUE THREAD

**Issue by Jay-9527** [tonquer/JMComic-qt#46]
### 操作系统（如MacOS 10.15）
>

### 网络环境（移动，联通，电信，移动宽带，联通宽带，电信宽带，等等..）
>

### 问题描述（简要描述发生的问题）
> 下载打开后显示的是Icns格式。并不是App格式

### 复现步骤（详细描述导致问题产生的操作步骤，如果能稳定复现）
>
下载好打开所展示的内容为：
![截屏2023-03-06 上午7 12 47](https://user-images.githubusercontent.com/30925620/222991434-64f8eff5-564f-47fc-a935-ada0245c1753.png)

### 日志提交（问题截图或者日志，日志在logs目录）
>
![截屏2023-03-06 上午7 12 04](https://user-images.githubusercontent.com/30925620/222991399-9fc26d0b-c27e-4f15-a75e-f329ef14a5f8.png)

**Comment by tonquer** [comment]
往下滑看看呢
