### ISSUE TITLE
打开我的收藏后崩溃

### ISSUE THREAD

**Issue by MAKE-ALEX** [tonquer/JMComic-qt#5]
### 操作系统（如MacOS 10.15）
>

windows 10 21H2
### 网络环境（移动，联通，电信，移动宽带，联通宽带，电信宽带，等等..）
>
联通

### 问题描述（简要描述发生的问题）
>
进入我的收藏界面卡死,内存需求持续增加.

### 复现步骤（详细描述导致问题产生的操作步骤，如果能稳定复现）
>
启动软件,点击我的收藏,加载中,程序无响应,内存持续增加.

### 日志提交（问题截图或者日志，日志在logs目录）
>
![屏幕截图 2022-03-18 041058](https://user-images.githubusercontent.com/57674781/158887492-9458839c-63a0-496b-a635-209a8f2b762d.jpg)

[20220318.log](https://github.com/tonquer/JMComic-qt/files/8291068/20220318.log)

**Comment by tonquer** [comment]
估计死循环了，我看看

**Comment by tonquer** [comment]
v1.0.4版本修复了这个问题
