### ISSUE TITLE
注册时的验证码在哪里获取？发送邮箱验证一直显示网络错误

### ISSUE THREAD

**Issue by Rosa712** [tonquer/JMComic-qt#53]
### 操作系统（如MacOS 10.15）
>windows10

### 网络环境（移动，联通，电信，移动宽带，联通宽带，电信宽带，等等..）
>校园网

### 问题描述（简要描述发生的问题）
>发送邮箱验证一直显示网络错误，是注册时要挂梯子吗？

### 复现步骤（详细描述导致问题产生的操作步骤，如果能稳定复现）
>

### 日志提交（问题截图或者日志，日志在logs目录）
>

**Comment by 1928544xj** [comment]
win10 移动宽带 发送邮箱验证一直显示网络错误，是注册时要挂梯子吗？
[20230511.log](https://github.com/tonquer/JMComic-qt/files/11447730/20230511.log)

**Comment by tonquer** [comment]
> win10 移动宽带 发送邮箱验证一直显示网络错误，是注册时要挂梯子吗？ [20230511.log](https://github.com/tonquer/JMComic-qt/files/11447730/20230511.log)

如何你网页可以访问，可以试试在网页版注册https://18comic.vip
