### ISSUE TITLE
本地收藏功能

### ISSUE THREAD

**Issue by mx41shy** [tonquer/JMComic-qt#56]
### 功能描述（请清晰的、详细的描述你想要的功能）
> 
JM这边官方收藏数量比较少。
希望可以新增把漫画收藏到本地功能，读取本地的收藏列表，点击本地的收藏跳转时再搜索对应的项目进行跳转

### 附加信息（其他的与功能相关的附加信息）
> 无

### 效果演示（可以提供可借鉴的图片）
>https://github.com/xiaoyaocz/flutter_dmzj
![61beb9a15d1b879a3931c36c07b825b](https://github.com/tonquer/JMComic-qt/assets/16437280/915e5789-0963-4f59-8d9a-9669796eb5b3) 
![04e2f5322e41b428c90578852196f76](https://github.com/tonquer/JMComic-qt/assets/16437280/05312adf-825b-4e76-944a-ce3f46470632)

**Comment by tonquer** [comment]
可以

**Comment by tonquer** [comment]
已解决
