### ISSUE TITLE
更新V1.1.0后图片分割错误

### ISSUE THREAD

**Issue by heihuan125** [tonquer/JMComic-qt#58]
### 操作系统（如MacOS 10.15）
>win10

### 网络环境（移动，联通，电信，移动宽带，联通宽带，电信宽带，等等..）
>联通

### 问题描述（简要描述发生的问题）
>更新后测试图片分割错误 如id454000前 400000后 其他未经测试 最新首页上的不受影响 应该类似1.0.8的情况
覆盖回1.0.9后图片加载正常

### 复现步骤（详细描述导致问题产生的操作步骤，如果能稳定复现）
>

### 日志提交（问题截图或者日志，日志在logs目录）
>

**Comment by tonquer** [comment]
是看已经下载的本子会这样吗

**Comment by heihuan125** [comment]
哦抱歉 试了下确实是已下载的才会这样 应当是会默认加载本地下载的图片
导致下载后阅读就会出现图片分割错乱 删除下载再阅读就会正常
用本地图片阅览器打开下载的图片看是正常的
试了下最新上传的也会出现这个情况

**Comment by heihuan125** [comment]
**问题描述（简要描述发生的问题）**
更新1.1.0后 已经下载到本地的漫画章节
点 阅读 看的时候 是会出现我之前描述的图片分割错误 
点 已下载章节 看的时候 会弹这个图片内的报错
用本地的图片阅览器看 下载的图片 是正常的
**复现步骤（详细描述导致问题产生的操作步骤，如果能稳定复现）**
搜索点击任一漫画详情 点击下载至本地
分别从阅读和已下载章节点开下载的章节
**日志提交（问题截图或者日志，日志在logs目录）**
![111](https://github.com/tonquer/JMComic-qt/assets/25154509/e2b0bd5a-77e1-455f-8023-b82260d7a6b5)
[20230614.log](https://github.com/tonquer/JMComic-qt/files/11745452/20230614.log)

**Comment by tonquer** [comment]
试试新的
https://github.com/tonquer/JMComic-qt/releases/tag/v1.1.1

**Comment by heihuan125** [comment]
没问题了 谢谢你
