### ISSUE TITLE
JM自定义CDN分流错误

### ISSUE THREAD

**Issue by matocool** [tonquer/JMComic-qt#59]
### 操作系统（如MacOS 10.15）
>win10

### 网络环境（移动，联通，电信，移动宽带，联通宽带，电信宽带，等等..）
>移动

### 问题描述（简要描述发生的问题）
>JM自定义CDN分流，修改之后，无法保存。重启电脑，重启软件均无效。

### 复现步骤（详细描述导致问题产生的操作步骤，如果能稳定复现）

1、先用任意可用默认节点登入，
2、用 CloudflareST_windows_386 测试出可用的快速节点 
3、然后点击CDN进行修改保存。提示保存成功。但是实际上并未成功。关闭软件再打开还是无法使用的CDN节点，而不是新修改的节点

### 日志提交（问题截图或者日志，日志在logs目录）
>
[20230613.log](https://github.com/tonquer/JMComic-qt/files/11726686/20230613.log)

**Comment by tonquer** [comment]
试试新的
https://github.com/tonquer/JMComic-qt/releases/tag/v1.1.1

**Comment by tonquer** [comment]
已解决
