### ISSUE TITLE
下载记录丢失

### ISSUE THREAD

**Issue by 3232154233** [tonquer/JMComic-qt#61]
### 操作系统（如MacOS 10.15）
>window 10

### 网络环境（移动，联通，电信，移动宽带，联通宽带，电信宽带，等等..）
>电信

### 问题描述（简要描述发生的问题）
>
下载记录丢失

### 复现步骤（详细描述导致问题产生的操作步骤，如果能稳定复现）
>
下载新的后，重启程序，发现记录消失，但下载的文件还在

### 日志提交（问题截图或者日志，日志在logs目录）
>
![)6_I SBHE8W{64 `K@7CH_M](https://github.com/tonquer/JMComic-qt/assets/138392241/36aca8af-fd88-4b3f-823b-55f9fd9517c0)
![RX6WW86_2R{5H LUSI O%KM](https://github.com/tonquer/JMComic-qt/assets/138392241/194a9274-6fd7-4809-a704-94b385c93b50)

```

**Comment by tonquer** [comment]
修复了
https://github.com/tonquer/JMComic-qt/actions/runs/5444998899

**Comment by 3232154233** [comment]
谢谢
