### ISSUE TITLE
可以增加一个修改域名ip的功能吗

### ISSUE THREAD

**Issue by wdnmdXD111** [tonquer/JMComic-qt#64]
### 功能描述（请清晰的、详细的描述你想要的功能）
> 增加一个修改域名ip的功能

### 附加信息（其他的与功能相关的附加信息）
> 像e-hentai一一样

### 效果演示（可以提供可借鉴的图片）
>
![image](https://github.com/tonquer/JMComic-qt/assets/106909709/8405b8e2-d4f8-4aa7-bf98-a4d43376ed99)

**Comment by tonquer** [comment]
分流里的cdn分流，就是可以修改ip的
