### ISSUE TITLE
反复出现网络错误

### ISSUE THREAD

**Issue by jogGUY** [tonquer/JMComic-qt#65]
### 操作系统（如MacOS 10.15）
>Windows 11

### 网络环境（移动，联通，电信，移动宽带，联通宽带，电信宽带，等等..）
>电信

### 问题描述（简要描述发生的问题）
>无法浏览、无法登录、分流设置中无法测速

### 复现步骤（详细描述导致问题产生的操作步骤，如果能稳定复现）
>

### 日志提交（问题截图或者日志，日志在logs目录）
>
![test_error](https://github.com/tonquer/JMComic-qt/assets/108516858/11c36202-ca92-4727-8a43-e26a6469cdb9)
![login_error](https://github.com/tonquer/JMComic-qt/assets/108516858/b1874b48-2b08-49f2-bfa1-4e885a72cf8e)
![browser_error](https://github.com/tonquer/JMComic-qt/assets/108516858/f105dae2-01f8-44c9-aedf-e9b9afb115bd)
[20230713.log](https://github.com/tonquer/JMComic-qt/files/12031368/20230713.log)

**Comment by tonquer** [comment]
jm服务器的问题
