### ISSUE TITLE
下载

### ISSUE THREAD

**Issue by North-ocean0** [tonquer/JMComic-qt#66]
### 操作系统（如MacOS 10.15）
>Windows11

### 网络环境（移动，联通，电信，移动宽带，联通宽带，电信宽带，等等..）
>移动，网络流畅

### 问题描述（简要描述发生的问题）
>下载功能异常，部分资源下载速度恒为0b/s，部分资源下载到一定页数速度变为0b/s并保持不变，部分资源可以下载

### 复现步骤（详细描述导致问题产生的操作步骤，如果能稳定复现）
>多次下载同一资源，仍产生问题
重启电脑与路由器均无效

### 日志提交（问题截图或者日志，日志在logs目录）
>
[20230715.log](https://github.com/tonquer/JMComic-qt/files/12063776/20230715.log)
[20230716.log](https://github.com/tonquer/JMComic-qt/files/12063777/20230716.log)

**Comment by North-ocean0** [comment]
同时在重新打开应用后，下载记录会丢失

**Comment by tonquer** [comment]
修复了
https://github.com/tonquer/JMComic-qt/releases/tag/v1.1.2
