### ISSUE TITLE
无法登陆，提示解析出错了

### ISSUE THREAD

**Issue by Requiem-X** [tonquer/JMComic-qt#67]
### 操作系统（如MacOS 10.15）
>
WIN10

### 网络环境（移动，联通，电信，移动宽带，联通宽带，电信宽带，等等..）
>
电信宽带

### 问题描述（简要描述发生的问题）
>
无法登陆，提示解析出错了。

### 复现步骤（详细描述导致问题产生的操作步骤，如果能稳定复现）
>
我是使用v2ray翻墙，JMComic-qt使用的是v1.1.2。
API分流里1 2 3 4 和默认CDN延迟均为错误，使用CloudflareST测试后更换所有ip均为错误。

### 日志提交（问题截图或者日志，日志在logs目录）
>
![1](https://github.com/tonquer/JMComic-qt/assets/71003845/92409102-9237-4f55-bacb-f53b41a648cf)
----
已解决

**Comment by DFYun123** [comment]
+1

**Comment by justhobby** [comment]
+1

**Comment by justhobby** [comment]
ok了，谢谢大佬
