### ISSUE TITLE
希望能加入webp转bmp/jpg功能

### ISSUE THREAD

**Issue by fuchaohan** [tonquer/JMComic-qt#68]
### 功能描述（请清晰的、详细的描述你想要的功能）
> 下载后webp转bmp/jpg功能

### 附加信息（其他的与功能相关的附加信息）
> 
现在下载下来的本子都是webp格式，对很多旧app和软件非常不友好，webp格式在局域网下我用smb访问不能快速切换图片
### 效果演示（可以提供可借鉴的图片）
>

**Comment by tonquer** [comment]
请更新v1.1.5试试
