### ISSUE TITLE
打开和关闭时的问题

### ISSUE THREAD

**Issue by o-qAp-o** [tonquer/JMComic-qt#69]
### 操作系统
>Win10

### 网络环境
>电信宽带

### 问题描述（简要描述发生的问题）

1. >直接双击打开程序等待多时且无法开启，管理员身份打开成功，但会报错（日志其一）（报错次数和双击打开尝试次数一致）
2. > app内部开启了退出时最小化到托盘，此时点击关闭不能正常到托盘，且报错（日志其二）（最初设置后好像没有问题，关闭该功能后不报错）

### 复现步骤（详细描述导致问题产生的操作步骤，如果能稳定复现）
>同上

### 日志提交（问题截图或者日志，日志在logs目录）

1. >日志中没有记录，此为弹窗内容：
Unhandled exception in script
Failed to execute script 'start' due to unhandled exception: name 'exit' is not defined
Traceback (most recent call last):
File "start.py", line 66, in <module>
NameError: name 'exit' is not defined

2. >2023-08-14 01:22:12,045 - start.py[line:92] - ERROR: Traceback (most recent call last):
  File "view\main\main_view.py", line 305, in closeEvent
AttributeError: 'QtOwner' object has no attribute 'closeType'
NoneType: None

**Comment by tonquer** [comment]
请更新v1.1.5试试
