### ISSUE TITLE
无法登陆

### ISSUE THREAD

**Issue by Junneeeee** [tonquer/JMComic-qt#7]
### 操作系统（如MacOS 10.15）
>
macOS 10.14

### 网络环境（移动，联通，电信，移动宽带，联通宽带，电信宽带，等等..）
>移动宽带

### 问题描述（简要描述发生的问题）
>今天中午登陆显示解析错误，进不去

### 复现步骤（详细描述导致问题产生的操作步骤，如果能稳定复现）
上午是可以看的，中午登陆的时候显示解析错误，怎么也打不开

### 日志提交（问题截图或者日志，日志在logs目录）
>

**Comment by Junneeeee** [comment]
这样![屏幕快照 2022-04-11 下午2 19 11](https://user-images.githubusercontent.com/103407116/162676514-0e119917-f1c4-4ced-b6f2-5b46fc70902e.png)

**Comment by Junneeeee** [comment]
网络状况
![屏幕快照 2022-04-11 下午2 22 00](https://user-images.githubusercontent.com/103407116/162676771-d703981c-8293-416b-8417-b9ddde0760f5.png)
网络![屏幕快照 2022-04-11 下午2 21 23](https://user-images.githubusercontent.com/103407116/162676754-8b95abd2-452c-4d20-a9c2-db91c6934b09.png)

**Comment by GuoZiAng** [comment]
<img width="1274" alt="截屏2023-01-21 05 33 13" src="https://user-images.githubusercontent.com/31526570/213809467-ba2cc8b6-54e3-43c8-abc2-509543d027f2.png">
兄弟，请问这没有发送验证码的按钮哇 ，怎么注册
