### ISSUE TITLE
部分漫画话数对应关系错位

### ISSUE THREAD

**Issue by ParanoiaIsGreat** [tonquer/JMComic-qt#72]
### 操作系统（如MacOS 10.15）
>WIn10

### 网络环境（移动，联通，电信，移动宽带，联通宽带，电信宽带，等等..）
>联通

### 问题描述（简要描述发生的问题）
>《美丽新世界》，缺少第46话，导致后续话数错位；《秘密教学》，缺少第106话，后续同样错位。同样的问题应该还有。导致最后几话无法观看。

### 复现步骤（详细描述导致问题产生的操作步骤，如果能稳定复现）
>

### 日志提交（问题截图或者日志，日志在logs目录）
>
![image](https://github.com/tonquer/JMComic-qt/assets/10475153/03a5d022-0b0a-4fe4-9ac7-467d79058abd)

![image](https://github.com/tonquer/JMComic-qt/assets/10475153/a8418a53-fac5-4e49-bb61-b34a5886a84c)

**Comment by hect0x7** [comment]
这应该不算bug，算是禁漫的问题。
比如`第107話 108 光看到子豪就濕了`，可以理解为，`第107話`是禁漫网站自己数据库的排序，`108`才是真正官方漫画的章节序号

**Comment by ParanoiaIsGreat** [comment]
> 这应该不算bug，算是禁漫的问题。 比如`第107話 108 光看到子豪就濕了`，可以理解为，`第107話`是禁漫网站自己数据库的排序，`108`才是真正官方漫画的章节序号

你没理解我意思，你自己试一下就知道了
按你说的没问题的话，那为什么最后几话看不了？比如《美丽新世界》第185话_205，点进去是第182话_203？

**Comment by hect0x7** [comment]
> > 这应该不算bug，算是禁漫的问题。 比如`第107話 108 光看到子豪就濕了`，可以理解为，`第107話`是禁漫网站自己数据库的排序，`108`才是真正官方漫画的章节序号
> 
> 你没理解我意思，你自己试一下就知道了 按你说的没问题的话，那为什么最后几话看不了？比如《美丽新世界》第185话_205，点进去是第182话_203？

你所说的`导致最后几话无法观看。`，你认为原因是`缺话数`，其实不是，只是因为禁漫命名奇怪让你产生了缺话数的错觉。你访问禁漫网页版就知道了，网页上命名看起来也缺话数，但是都能看，所以归因为缺话数是不对的。
所以到底为什么客户端看不了最后几话，这个应该真的是程序bug。我测了API返回值，497550对应第185話 205，486309对应第182話 203，程序显然把章节id的对应关系搞错了。

**Comment by tonquer** [comment]
请更新v1.1.5试试
