### ISSUE TITLE
有的漫画再特定章节的固定漫画页卡住，下载速度为0或着直接错误

### ISSUE THREAD

**Issue by yubinquankuang** [tonquer/JMComic-qt#73]
### 操作系统（如MacOS 10.15）
>win10

### 网络环境（移动，联通，电信，移动宽带，联通宽带，电信宽带，等等..）
>

### 问题描述（简要描述发生的问题）
>

### 复现步骤（详细描述导致问题产生的操作步骤，如果能稳定复现）
>

### 日志提交（问题截图或者日志，日志在logs目录）
>
![捕获](https://github.com/tonquer/JMComic-qt/assets/39264014/ef098026-56bc-4553-be3d-88cb48ffc7ca)

**Comment by tonquer** [comment]
请更新v1.1.5试试
