### ISSUE TITLE
登录时出现解析错误

### ISSUE THREAD

**Issue by wulianwang955** [tonquer/JMComic-qt#74]
### 操作系统（如MacOS 10.15）
>
windows10

### 网络环境（移动，联通，电信，移动宽带，联通宽带，电信宽带，等等..）
>
移动

### 问题描述（简要描述发生的问题）
>
登录时出现解析错误，即使不登录也无法查看本子，依旧出现为解析错误

### 复现步骤（详细描述导致问题产生的操作步骤，如果能稳定复现）
>

### 日志提交（问题截图或者日志，日志在logs目录）
>

**Comment by tonquer** [comment]
换分流

**Comment by ericvlog** [comment]
> 换分流

换了也不行。

**Comment by tonquer** [comment]
更新试试
https://github.com/tonquer/JMComic-qt/releases/tag/v1.1.6
