### ISSUE TITLE
注册时的图片验证码不显示

### ISSUE THREAD

**Issue by AugustNANA** [tonquer/JMComic-qt#75]
### 操作系统（如MacOS 10.15）
>WIN11

### 网络环境（移动，联通，电信，移动宽带，联通宽带，电信宽带，等等..）
>联通宽带

### 问题描述（简要描述发生的问题）
>在使用VPN时，验证码图片区域空白，没有显示

### 复现步骤（详细描述导致问题产生的操作步骤，如果能稳定复现）
>

### 日志提交（问题截图或者日志，日志在logs目录）
>
![image](https://github.com/tonquer/JMComic-qt/assets/149290197/4e7931f6-6725-4b66-a93d-a859d390e281)

**Comment by tonquer** [comment]
现在只能自行在网页注册，18comic.vip
