### ISSUE TITLE
新版本如何兼容老版本的已下载漫画

### ISSUE THREAD

**Issue by wuweihao777** [tonquer/JMComic-qt#78]
### 操作系统（如MacOS 10.15）
>
win11

### 网络环境（移动，联通，电信，移动宽带，联通宽带，电信宽带，等等..）
>

### 问题描述（简要描述发生的问题）
>
需要跟新新版本 但是不知道老版本的下载内容如何移植到新版本

### 复现步骤（详细描述导致问题产生的操作步骤，如果能稳定复现）
>

### 日志提交（问题截图或者日志，日志在logs目录）
>

**Comment by tonquer** [comment]
覆盖start.exe就行了吧

**Comment by wuweihao777** [comment]
OK 刚刚才发现文档下面写了目录覆盖 谢谢  另外想问下佬  用waifu2x文件损坏是什么情况

**Comment by tonquer** [comment]
没看见你上传的图

**Comment by wuweihao777** [comment]
![Uploading 微信截图_20231103232831.png…]()

**Comment by wuweihao777** [comment]
[image: 微信截图_20231103232831.png]

tonquer ***@***.***> 于2023年11月3日周五 23:37写道：
