### ISSUE TITLE
假死问题可否得到修复

### ISSUE THREAD

**Issue by matocool** [tonquer/JMComic-qt#8]
### 操作系统（如MacOS 10.15）
>10 21H2

### 网络环境（移动，联通，电信，移动宽带，联通宽带，电信宽带，等等..）
>
移动宽带

### 问题描述（简要描述发生的问题）
>
假死问题可否得到修复

### 复现步骤（详细描述导致问题产生的操作步骤，如果能稳定复现）
>下载时候容易假死

### 日志提交（问题截图或者日志，日志在logs目录）
>
无

**Comment by matocool** [comment]
200MB移动+32G 3200+3600X 

这些配置肯定是没问题的。。。。。。。BIOS虚拟已开启

但是还是会假死，任务管理器占用也不高，正常。。。为何会假死。。。兼容性问题嘛

**Comment by matocool** [comment]
同时下载错误也经常出现，看了下别人的反馈。应该跟网络无关，大概率是反爬虫机制。建议这边一旦下载错误，过1分钟后自动修正为继续下载，而不用每次都要挂在前端去不停地盯着。。。

错误之后再次点击下载是可以继续下载的，应该是服务器的反扒机制。

**Comment by tonquer** [comment]
假死是啥意思，界面无响应吗

**Comment by matocool** [comment]
> 假死是啥意思，界面无响应吗

对，而且会卡顿 有时候。

**Comment by tonquer** [comment]
有空我查一查

**Comment by matocool** [comment]
![image](https://user-images.githubusercontent.com/83129369/164121148-bcddbb99-e8cc-417f-815b-75ba9add408a.png)

**Comment by matocool** [comment]
> 有空我查一查

请看图

**Comment by matocool** [comment]
> > > 有空我查一查
> > 
> > 
> > 请看图
> 
> 你这时候是在下载吗

无论是否下载，都有概率假死。偶尔还会整个软件直接闪退。

**Comment by matocool** [comment]
![$9RSOFB7Y(DHONNNP64~IUY](https://user-images.githubusercontent.com/83129369/164405555-50524104-e9c4-43ab-8e42-500057acaa58.png)
![@ V5WSO}BX7I`99 QEWEMO](https://user-images.githubusercontent.com/83129369/164405702-aea1c64e-a485-4628-aea0-6acce94faace.png)
![}6R~7F$)`4O0INZERRH~XG](https://user-images.githubusercontent.com/83129369/164405747-0b50596e-1181-4c79-8ce4-7d8a22d2f898.png)

**Comment by matocool** [comment]
![9TQ5Z(AHR}UVU{U5971)Z3U](https://user-images.githubusercontent.com/83129369/164405866-887a7c57-6448-44d3-a839-d20c18997f66.png)

**Comment by tonquer** [comment]
感谢提供

**Comment by matocool** [comment]
已修复，此贴终结。
