### ISSUE TITLE
解析出错了

### ISSUE THREAD

**Issue by chxip** [tonquer/JMComic-qt#80]
### 操作系统（如MacOS 10.15）
>

### 网络环境（移动，联通，电信，移动宽带，联通宽带，电信宽带，等等..）
>

### 问题描述（简要描述发生的问题）
>

### 复现步骤（详细描述导致问题产生的操作步骤，如果能稳定复现）
>所有页面功能都提示 解析出错了

### 日志提交（问题截图或者日志，日志在logs目录）
>

**Comment by Gackle** [comment]
稍微看了一下 log ，登录是成功的了但是 `user = ToolUtil.ParseLogin2(task.req.ParseData(v.get("data")))` (user_handler.py) 里面做了解密之后 decode 不出来，看上去好像是加密方式变了（误）

**Comment by chxip** [comment]
求大佬修复T_T

**Comment by tonquer** [comment]
加密方式似乎又变了，待修复

**Comment by hect0x7** [comment]
可以试试看这个 https://github.com/hect0x7/JMComic-qt/actions/runs/6955859581
