### ISSUE TITLE
Failed to boot

### ISSUE THREAD

**Issue by HenryZNNUE** [tonquer/JMComic-qt#85]
### 操作系统（如MacOS 10.15）
>Win11 23H2 22631.3085

### 网络环境（移动，联通，电信，移动宽带，联通宽带，电信宽带，等等..）
>CTM

### 问题描述（简要描述发生的问题）
>tonquer's jmcomic, picacg, ehentai双击后任务栏显示无图标界面后闪退，之前在CTM环境下都可以正常观看，不知是否为jm本身的问题

### 复现步骤（详细描述导致问题产生的操作步骤，如果能稳定复现）
>暂时无法在其他运营商网络下测试

### 日志提交（问题截图或者日志，日志在logs目录）
>2024-01-31 17:25:22,285 - start.py[line:71] - WARNING: init scene ratio: 1.5
2024-01-31 17:25:23,165 - download_db.py[line:45] - WARNING: duplicate column name: tick Unable to execute statement

**Comment by tonquer** [comment]
是打开界面不显示吗

**Comment by HenryZNNUE** [comment]
![issue](https://github.com/tonquer/JMComic-qt/assets/106044981/28ed45df-a188-46ce-9773-1c9a2ee78c42)

**Comment by HenryZNNUE** [comment]
暂时无法在中国移动等其他运营商网络下测试

**Comment by tonquer** [comment]
有操作啥嘛，重启系统也是无法打开吗

**Comment by HenryZNNUE** [comment]
除了更新至Win11 23H2最新版本系统、关闭内存完整性，启用Huge Pages，以及更新了第三方杀毒软件（已验证不会产生影响）外，没有其他操作。刚刚多次尝试打开后发现偶尔可以打开界面，但是所有api分流显示网络错误；似乎有些用户目前也无法连接到jm，能否验证问题是否出自jm网站？
![issue](https://github.com/tonquer/JMComic-qt/assets/106044981/2b4d8788-6676-49d8-b05b-127e45efbb21)

**Comment by tonquer** [comment]
分流正在修复，等下更新

**Comment by HenryZNNUE** [comment]
好的
猜测原因可能是各个相关网站流量收到影响

**Comment by tonquer** [comment]
发布了可以试试
https://github.com/tonquer/JMComic-qt/releases/tag/v1.1.9

**Comment by HenryZNNUE** [comment]
登录进去了一次，然后又不行了
以下是对1.1.8.1的IDA反汇编：
__int64 __fastcall sub_7FF7EC8B1050(FILE **a1, __int64 a2, FILE *a3, char *a4)
{
  FILE **v6; // rdi
  void *v8; // rbp
  unsigned int v9; // eax
  unsigned int v10; // r15d
  void *v12; // r13
  unsigned __int64 v13; // r12
  size_t v14; // rbx
  unsigned int v15; // eax
  unsigned int v16; // edi
  size_t v17; // rbx
  void *v18; // [rsp+20h] [rbp-98h] BYREF
  int v19; // [rsp+28h] [rbp-90h]
  void *v20; // [rsp+30h] [rbp-88h]
  unsigned int v21; // [rsp+38h] [rbp-80h]
  __int64 v22; // [rsp+50h] [rbp-68h]
  __int64 v23; // [rsp+58h] [rbp-60h]
  __int64 v24; // [rsp+60h] [rbp-58h]

  v22 = 0i64;
  v6 = a1;
  v23 = 0i64;
  v24 = 0i64;
  v19 = 0;
  v18 = 0i64;
  v8 = 0i64;
  v9 = sub_7FF7EC8B9350(&v18, "1.2.11", 88i64);
  v10 = v9;
  if ( v9 )
  {
    sub_7FF7EC8B2760("Failed to extract %s: inflateInit() failed with return code %d!\n", (const char *)(a2 + 18), v9);
    return 0xFFFFFFFFi64;
  }
  else
  {
    v12 = j__malloc_base(0x2000ui64);
    if ( v12 )
    {
      v8 = j__malloc_base(0x2000ui64);
      if ( v8 )
      {
        v13 = *(unsigned int *)(a2 + 8);
LABEL_8:
        v14 = v13;
        if ( v13 > 0x2000 )
          v14 = 0x2000i64;
        if ( fread(v12, 1ui64, v14, *v6) != v14 || ferror(*v6) )
        {
          v10 = -1;
        }
        else
        {
          v13 -= v14;
          v19 = v14;
          v18 = v12;
          while ( 1 )
          {
            v20 = v8;
            v21 = 0x2000;
            v15 = sub_7FF7EC8B7810(&v18, 0i64);
            v16 = v15;
            v10 = -1;
            if ( v15 + 4 <= 2 )
              break;
            if ( v15 == 2 )
            {
              v16 = -3;
              break;
            }
            v17 = 0x2000i64 - v21;
            if ( a3 )
            {
              if ( fwrite(v8, 1ui64, v17, a3) != v17 || ferror(a3) )
              {
                v16 = -1;
                break;
              }
            }
            else if ( a4 )
            {
              memmove(a4, v8, v17);
              a4 += v17;
            }
            if ( v21 )
            {
              if ( v16 == 1 )
              {
                v10 = 0;
                goto LABEL_29;
              }
              if ( v13 )
              {
                v6 = a1;
                goto LABEL_8;
              }
              break;
            }
          }
          sub_7FF7EC8B2760(
            "Failed to extract %s: decompression resulted in return code %d!\n",
            (const char *)(a2 + 18),
            v16);
        }
      }
      else
      {
        sub_7FF7EC8B24C0(
          "malloc",
          "Failed to extract %s: failed to allocate temporary output buffer!\n",
          (const char *)(a2 + 18));
      }
    }
    else
    {
      sub_7FF7EC8B24C0(
        "malloc",
        "Failed to extract %s: failed to allocate temporary input buffer!\n",
        (const char *)(a2 + 18));
    }
LABEL_29:
    sub_7FF7EC8B9040(&v18);
    free(v12);
    free(v8);
    return v10;
  }
}
可能是内存分配问题，我现在试一下恢复内存完整性，关闭Huge Pages

**Comment by HenryZNNUE** [comment]
更改系统设置后依然是偶尔能打开
日志：
2024-01-31 23:06:10,735 - start.py[line:71] - WARNING: init scene ratio: 1.5
2024-01-31 23:06:11,819 - download_db.py[line:45] - WARNING: duplicate column name: tick Unable to execute statement

**Comment by tonquer** [comment]
你设置里设置了关闭后最小化到托盘吗

**Comment by HenryZNNUE** [comment]
好像没有，目前无法确认；启动后任务管理器会新增两个start.exe进程，托盘中会新增图标，但马上都会消失

**Comment by tonquer** [comment]
https://github.com/tonquer/JMComic-qt/releases/download/v1.1.9/jmcomic_v1.1.9_windows7_x64.zip

**Comment by HenryZNNUE** [comment]
是，之前使用都没有问题；几个星期之后就这样了

**Comment by tonquer** [comment]
感觉是你内存坏了一根的样子，软件扫下内存看看报不报错

**Comment by HenryZNNUE** [comment]
任务管理器显示64GB，应该没问题？

**Comment by tonquer** [comment]
好像有个叫memory test的软件，可以扫描内存是否有坏块

**Comment by HenryZNNUE** [comment]
有没有某些win11设置可能导致运行问题？

**Comment by HenryZNNUE** [comment]
问题目前已解决，是AMD核显驱动版本导致的，如果有相同问题的用户看到的话，请前往AMD Software更新驱动

**Comment by tonquer** [comment]
原来是显卡驱动的问题，应该是Waifu2x模块冲突了导致的
