### ISSUE TITLE
api分流网络错误

### ISSUE THREAD

**Issue by windcat007** [tonquer/JMComic-qt#86]
### 操作系统（如MacOS 10.15）
>Windows 10

### 网络环境（移动，联通，电信，移动宽带，联通宽带，电信宽带，等等..）
>电信宽带 移动宽带

### 问题描述（简要描述发生的问题）
>api分流网络错误

### 复现步骤（详细描述导致问题产生的操作步骤，如果能稳定复现）
>点击登录显示网络错误，分流页面测速，api分流都是网络错误，图片分流正常。加不加代理都一样。

### 日志提交（问题截图或者日志，日志在logs目录）
>![Snipaste_2024-01-31_20-41-30](https://github.com/tonquer/JMComic-qt/assets/44797595/cab35a1a-0404-4c68-8ed8-cee08221998a)

**Comment by ericvlog** [comment]
我也是这个错误啊。

**Comment by imnontenper** [comment]
同上

**Comment by tonquer** [comment]
分流更新了，正在修复

**Comment by tonquer** [comment]
发布了，可以试试
https://github.com/tonquer/JMComic-qt/releases/tag/v1.1.9

**Comment by imnontenper** [comment]
可以了谢谢

> 发布了，可以试试 [https://github.com/tonquer/JMComic-qt/releases/tag/v1.1.9](https://hub.ggo.icu/tonquer/JMComic-qt/releases/tag/v1.1.9)
