### ISSUE TITLE
解析出错了

### ISSUE THREAD

**Issue by ruihanlee95** [tonquer/JMComic-qt#88]
### 操作系统（如MacOS 10.15）
>MacOS13.6.3

### 网络环境（移动，联通，电信，移动宽带，联通宽带，电信宽带，等等..）
>

### 问题描述（简要描述发生的问题）
>解析出错了

### 复现步骤（详细描述导致问题产生的操作步骤，如果能稳定复现）
>

### 日志提交（问题截图或者日志，日志在logs目录）
>
[20240215.log](https://github.com/tonquer/JMComic-qt/files/14298733/20240215.log)

**Comment by tonquer** [comment]
重新打包了

**Comment by tonquer** [comment]
v1.2.0修复
