### ISSUE TITLE
无法进行网页注册

### ISSUE THREAD

**Issue by hong090713** [tonquer/JMComic-qt#89]
### 操作系统（如MacOS 10.15）
>

### 网络环境（移动，联通，电信，移动宽带，联通宽带，电信宽带，等等..）
>

### 问题描述（简要描述发生的问题）
>选择注册界面的链接会显示无法访问网站，且我的邮箱未收到验证码，而在“验证”处选择发送邮箱验证会显示网络错误（不是很会用，也可能是我操作失误），求帮助

### 复现步骤（详细描述导致问题产生的操作步骤，如果能稳定复现）
>

### 日志提交（问题截图或者日志，日志在logs目录）
>

**Comment by tonquer** [comment]
现在注册只能在官网网页版注册，没办法

**Comment by hong090713** [comment]
> 现在注册只能在官网网页版注册，没办法

求个官网地址

**Comment by tonquer** [comment]
> > 现在注册只能在官网网页版注册，没办法
> 
> 求个官网地址

https://18comic.org/
https://18comic.vip/

**Comment by tonquer** [comment]
貌似改一下可以用，下个版本恢复注册功能

**Comment by hong090713** [comment]
> 貌似改一下可以用，下个版本恢复注册功能

先生大义！

**Comment by tonquer** [comment]
这个试试，18comic-palworld.club

**Comment by tonquer** [comment]
v1.2.0已支持
