### ISSUE TITLE
希望在设置里增加“封面图片”和“标题”自定义宽度的选项，目前设置的封面还是占用屏幕太大了

### ISSUE THREAD

**Issue by newnewword** [tonquer/JMComic-qt#90]
### 功能描述（请清晰的、详细的描述你想要的功能）
> 1.在当前版本中，封面图片最低只能设置百分之50，设置完后感觉还是太大了。
2.而且文字大小即使设置成最低的，还是会占用多行，综上来看导致一个屏幕只能看见一两行的封面内容。
希望以后的版本能让标题的文字可以占用一行的情况下调节大小
### 附加信息（其他的与功能相关的附加信息）
> 

### 效果演示（可以提供可借鉴的图片）
>类似于这样
![Screenshot_2024-02-27-01-21-30-38](https://github.com/tonquer/JMComic-qt/assets/123813188/25e298a2-e252-4c60-990e-6366e1f28cbf)

**Comment by tonquer** [comment]
是不是你系统缩放调的很大

**Comment by tonquer** [comment]
v1.2.1可以设置标题行数了
