### ISSUE TITLE
登录注册问题

### ISSUE THREAD

**Issue by Ankhbai** [tonquer/JMComic-qt#98]
### 操作系统（如MacOS 10.15）
>安卓

### 网络环境（移动，联通，电信，移动宽带，联通宽带，电信宽带，等等..）
>移动

### 问题描述（简要描述发生的问题）
>禁漫的注册以及登录显示404，无法登录查看。

### 复现步骤（详细描述导致问题产生的操作步骤，如果能稳定复现）
>更新链接：18comic.tw
>在浏览器可以查看登录以及注册。在软件修改设置Domain后，依然无法登录注册。
>因此，需要更改源码的URL。

### 日志提交（问题截图或者日志，日志在logs目录）
>

**Comment by tonquer** [comment]
本项目没有安卓版本吧，注册链接已经更新
