### ISSUE TITLE
网络错误

### ISSUE THREAD

**Issue by zzzzoip** [tonquer/JMComic-qt#99]
### 操作系统（如MacOS 10.15）
>windo11

### 网络环境（移动，联通，电信，移动宽带，联通宽带，电信宽带，等等..）
>联通

### 问题描述（简要描述发生的问题）
>网络一直显示错误

### 复现步骤（详细描述导致问题产生的操作步骤，如果能稳定复现）
>

### 日志提交（问题截图或者日志，日志在logs目录）
>
![屏幕截图 2024-04-20 190654](https://github.com/tonquer/JMComic-qt/assets/130232490/7141a824-7219-446c-8300-4ae6c1e4b693)

**Comment by tonquer** [comment]
是jm的问题，过会就会正常
